---
- name: testing
  hosts: localhost
  tasks:
  - name: Create Public S3 bucket
    amazon.aws.s3_bucket:
      #name: "{{ lookup('ansible.builtin.env', 'AWS_BUCKET') }}"
      name: gmidha-bigdata-nov07
      state: present
      region: us-east-2
      versioning: true 
      encryption: "AES256"
      public_access:
        block_public_acls: false
    register: s3bucket
  - name: Upload Data in S3 bucket
    shell: >
      aws s3 cp /Users/gmidha/Downloads/msft2d.csv s3://gmidha-bigdata-nov07/msft2d.csv
